[tool.black]
extend-exclude = '''
/(
  | remote/protobuf
)/
'''

[tool.isort]
profile = "black"
src_paths = ["src", "tests"]
extend_skip = ["src/tieba_thread_archive/remote/protobuf"]

[tool.pytest.ini_options]
pythonpath = "."
